site_name: Farmácia Popular do Brasil - Povos Originários

dev_addr: 127.0.0.1:8005

nav:
  - Home: index.md
  - PIFPBPO:
      - PIFPBPO001 - Autenticação e Autorização: pifpbpo/PIFPBPO001.md
      - PIFPBPO002 - Papéis e recursos: pifpbpo/PIFPBPO002.md
      - PIFPBPO003 - Atribuição de papéis a atores: pifpbpo/PIFPBPO003.md
      - PIFPBPO004 - Gestão de Farmácias/Drogarias Credenciadas ao Programa: pifpbpo/PIFPBPO004.md
  - Sobre:
      - Sobre o Projeto: sobre/sobre.md

theme:
  name: readthedocs
  logo: assets/img/logo.png

extra_css:
  - assets/css/extra.css

plugins:
  - search
  - mermaid2
